### ISSUE TITLE
Custom command placeholder isue <killer> and <participants-list>

### ISSUE THREAD

**Issue by rybuilder23** [evs-dev/EnderDragonTweaks#15]
when the custom command is excuted with placeholder <killer> or <participants-list>

It used the players nickname.

with many commands the nickname doest not work
you need the players username.

this can fix the probleem.
if it can be added?

<killer_nickname>
<killer_playername>

<participants-list_nickname> 
<participants-list_username>

**Comment by evs-dev** [comment]
Thanks for reporting! I think this is because I use `Player#getDisplayName()` instead of whatever method gets the actual username. I'll change it just for the command killer because you probably want nicknames to show in the defeat announcement message.

**Comment by rybuilder23** [comment]
yea  thats right!

**Comment by evs-dev** [comment]
Wait no I haven't fixed it yet, need to fix it for participants too, and how the killer is displayed. Whoops.
