### ISSUE TITLE
[isue] xp-per-player keeps at 68 levels 

### ISSUE THREAD

**Issue by rybuilder23** [evs-dev/EnderDragonTweaks#18]
the xp that the player gets is always 68xp levels.

i changed it to 25

# DEFAULT: 68
xp-per-player: 25

but the players keep getting 68xp levels

edit
with  xp mode:  points i also keep getting 68 levels

**Comment by evs-dev** [comment]
Just to confirm, you are on v1.2.1 and have updated your config? Do you get a warning in the console when you start the server about the config version?

**Comment by rybuilder23** [comment]
Yes i m on EnderDragonTweaks v1.2.1
and my config is updated to config version 2

**Comment by rybuilder23** [comment]
oeps

**Comment by evs-dev** [comment]
Ok thanks, I'll have a look. And when you change the value in the config and save, you are restarting the server?

**Comment by rybuilder23** [comment]
i have found the probleem

a big oef.

i use filezila for my servers
and i had a other server tab open so i was saving the file on the wrong server.
now that i saved the file on de right server it al works.
