### ISSUE TITLE
[idea] Respawn cooldown 

### ISSUE THREAD

**Issue by rybuilder23** [evs-dev/EnderDragonTweaks#19]
an cooldown on respawning the dragon with ender crystals 

just one of my ideas ;p

**Comment by evs-dev** [comment]
So like people can't continually respawn the Dragon to farm it? Interesting idea.

**Comment by rybuilder23** [comment]
Yes that's right.

I have now people that are respawning and killing the dragon hole day.

I have as reward for killing the dragon
A crate key with Manny rewards in it
And people want the rare rewards.


Many players love the plugin it makes the dragon fight more fun and exciting.

**Comment by evs-dev** [comment]
Ooh I see, that's quite a serious issue then. I'll get round to that at some point, thanks for suggesting the idea!

And that's cool to hear about your players - can I ask how many players you have typically online on your server?

**Comment by rybuilder23** [comment]
I have 9 to 13 hardcore players that almost always are online.

And when people come home after work it go to 20  but some players are going on Holliday's so it will drop a little.

**Comment by evs-dev** [comment]
Implemented in v1.3.0! https://github.com/evs-dev/EnderDragonTweaks/releases/tag/v1.3.0
