### ISSUE TITLE
Suggestion: Support for PlaceholderAPI

### ISSUE THREAD

**Issue by KiinoOFC** [evs-dev/EnderDragonTweaks#22]
If you have support with placeholderapi, it would help showing the enderdragon respawn time, or how many times the enderdragon died by the player and etc. ☕

**Comment by evs-dev** [comment]
There are no plans to support Placeholder API. I don't know how it works, but if there are commands for it, you can use the commands section of the EnderDragonTweaks config where you can use stats as placeholders.

**Comment by KiinoOFC** [comment]
ok
