### ISSUE TITLE
Placeholder Statistic

### ISSUE THREAD

**Issue by AnimeDrache** [evs-dev/EnderDragonTweaks#23]
Hey ♥,

this is just a suggestion: I wanted to setup a hovering text on my spawn where people can see the top killers name. But sadly there is no working placeholder like %dragonDeathCount% or something like that. It would be nice to use the statistics for hovering texts or for texts on signs!

**Comment by evs-dev** [comment]
Hi, have a look at [this](https://github.com/evs-dev/EnderDragonTweaks/blob/master/src/config.yml#L10). Then use the custom-commands section to set the text using whatever commands your plugin has, e.g. `/hovertext spawn_text set "Dragon deaths: <stat-dragonDeathCount>"`.
