### ISSUE TITLE
Port to 1.20.1 ?

### ISSUE THREAD

**Issue by Yokiie** [evs-dev/EnderDragonTweaks#26]
Hey,
I was wondering if you're planning on porting this mod to the newest Minecraft version 1.20.1 ?
I would really like to use this mod for my server but it doesn't seem to be available for 1.20.1 yet ?

**Comment by evs-dev** [comment]
Because of how Spigot works, I shouldn't need to do anything. Try the current version of the plugin which works for loads of versions already. Let me know how it goes and if there's a problem I'll fix it, else I'll update the compatible versions on the Spigot page.
