### ISSUE TITLE
[Enhancement] Only count players who's on the main island

### ISSUE THREAD

**Issue by Uboaaaaa** [evs-dev/EnderDragonTweaks#3]
When a dragon is killed, the reward is given to all players in anywhere in the end. Whoever is exploring the outer island, farming enderman at the enderman farm will all receive the experience reward, and will all be included in the kill broadcast.

Suggestion: For these features, only include players who's on the main island.

**Comment by evs-dev** [comment]
That's a great suggestion - it seems to be popular. In fact, someone made a PR (#2) to add this and I merged it with the dev branch. I just haven't got around to merging to master yet, so sorry about that. I'll try and do it this week, maybe today, but I think I want to do some code cleanup first.
