### ISSUE TITLE
[idea] Custom Rewards

### ISSUE THREAD

**Issue by rybuilder23** [evs-dev/EnderDragonTweaks#6]
perhaps a custom rewards option? 

When you kill the dragon that you get extra rewards ???

for example a few diamonds , gold ingot , some enchanted books etc

These are ideas and you don't have to do anything with them.

but you can use them :)

**Comment by evs-dev** [comment]
Hey thanks for the ideas - they're all quite interesting. It's great to see interest in the plugin.
This idea in particular is quite good, as I can imagine this would be very useful for a lot of people. It's a bit like [snr93's idea](https://www.spigotmc.org/threads/enderdragontweaks.458730/#post-3920083), but more specific. For this reason, I think if I implemented the ability to add commands to the config that are run by the server, it would be better than just a rewards system. How does that sound? So maybe:

```yml
commands:
 give <killer> minecraft:diamond 32
 give <other-fight-participants> minecraft:iron_ingot 16
 give <all-fight-participants> minecraft:dragon_egg 1
```

**Comment by rybuilder23** [comment]
Sounds good!
Especially with the placeholders!

I can think of multiple uses with this.

For example I can use a crate plugin and give people random rewards.

**Comment by evs-dev** [comment]
Ok cool! One problem I've had so far is that no matter what the command log appears in chat for all ops, do you think this would be a problem for you?

**Comment by rybuilder23** [comment]
It's no problem for me.

**Comment by evs-dev** [comment]
Ok cool, thanks!
