### ISSUE TITLE
[idea] dragon respawn on timer?

### ISSUE THREAD

**Issue by rybuilder23** [evs-dev/EnderDragonTweaks#7]
optional clock / timer that the dragon respawns? 

 like each XX hours XX minutes the dragon respawns if there is no dragon.
and when there is a dragon from the endercrystals that the timer is off?

These are ideas and you don't have to do anything with them.

but you can use them :)

**Comment by evs-dev** [comment]
This is very interesting as it means people don't have to get End Crystals to respawn the dragon. However, this seems like something that should be tackled by server owners as there's probably no perfect way to do this. I might add an easy way to initiate the spawn of the Dragon though.
Again thanks for all your ideas - they're very interesting to think about!

**Comment by evs-dev** [comment]
Is this still something you would like?

**Comment by rybuilder23** [comment]
its not needed it think i could also add a schedule in my server console.

and the players summon the hole day dragons.

**Comment by evs-dev** [comment]
Ok cool. I have added a cooldown in v1.3.0 which I will release soon. It's a big update I think.

**Comment by PystoyPlayer** [comment]
> Is this still something you would like?

Hello. Sorry, can you explain please how can I setup timer for dragon respawn ? So players won't need ender crystals

**Comment by evs-dev** [comment]
> > Is this still something you would like?
> 
> Hello. Sorry, can you explain please how can I setup timer for dragon respawn ? So players won't need ender crystals

Hi, this plugin doesn't have this feature as it's quite difficult to respawn the dragon in code. There might be another plugin that works, or perhaps command blocks could be use.
