### ISSUE TITLE
[idea] Custon dragon name?

### ISSUE THREAD

**Issue by rybuilder23** [evs-dev/EnderDragonTweaks#8]
ability to give the dragon a Cool custom name?

These are ideas and you don't have to do anything with them.

but you can use them :)

**Comment by evs-dev** [comment]
This is a good idea, but I'm not sure it fits with the idea of the plugin, which is to enhance the Dragon's death. Perhaps I could branch out into enhancing the Dragon fight in general. I'll think about it!
